import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../styles/scss/global.scss'
import Link from 'next/link'
import LeftMenu from '../components/templates/LeftMenu'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    
    return (
        <html lang="en">
            <body className={inter.className}>

                <div className="container_full head">
                    <div className="container head_col">
                        <div >
                            <div>
                                <img src="/icons/logo/logo1.png" alt='Logo' />
                            </div>
                            <div>
                                <h2 >OCALNII</h2>
                            </div>
                        </div>
                        <div >

                            <div className="menu">
                                <div title="Delivery Order">
                                    <button><i className="fa-solid fa-truck"></i></button>
                                    <button>2</button>
                                </div>
                                <div title="Sell Order">
                                    <button><i className="fa-solid fa-clipboard-check"></i></button>
                                    <button>2</button>
                                </div>
                                <div title="Messages">
                                    <button><i className="fa-solid fa-message"></i></button>
                                    <button>2</button>
                                </div>
                                <div title="Notification">
                                    <button><i className="fa-solid fa-bell"></i></button>
                                    <button>9+</button>
                                </div>
                                <div className="profile_img">
                                    <div>
                                        <div style={{ backgroundImage: `url(https://i.kinja-img.com/gawker-media/image/upload/c_fit,f_auto,g_center,q_60,w_645/0ac071df51837e4b91b71842ea368862.jpg)` }} ></div>
                                    </div>
                                    <div><i className="fa-solid fa-ellipsis-vertical"></i></div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>

                <div className="container_full">
                    <div className="container content_col">
                        <div className="col_left">

                            <div>
                                <div className="left_pin">
                                    <button><i className="fa-solid fa-street-view"></i> 783360</button>
                                </div>

                                <LeftMenu></LeftMenu>

                            </div>

                        </div>

                        {children}

                    </div>
                </div>

                
                
            </body>
        </html>
    )
}
