import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../styles/scss/global.scss'
import LeftMenu from '../components/templates/LeftMenu'
import MenuModal from '../components/form/MenuModal'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {

    return (
        <main>

            <div className={inter.className}>

                <MenuModal></MenuModal>

                <div className="container_full">
                    <div className="container content_col">
                        <div className="col_left">

                            <div>
                                
                                <LeftMenu></LeftMenu>

                            </div>

                        </div>

                        {children}

                    </div>
                </div>



            </div>

        </main>
    )
}
