import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../styles/scss/global.scss'
import LeftMenu from '../components/templates/LeftMenu'
import MenuModal from '../components/form/MenuModal'
import MainContent from '../components/templates/MainContent'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {

    return (
        <main>

            <div className={inter.className}>

                <MenuModal />

                <div className="container_full">
                    <div className="container content_col">
                
                        <MainContent></MainContent>

                        {children}

                    </div>
                </div>

                

            </div>

        </main>
    )
}
